name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  test:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com/
          scope: "@weglot"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Set version package
        run: npm version --no-git-tag-version ${{ github.ref_name }}

      - name: Publish on Github registry
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
